events {
    worker_connections 1024;
}
http {
    include mime.types;
    default_type application/octet-stream;
    upstream backend_servers {
        server 10.7.19.184:3001;
        server 10.7.13.88:3002;
    }
    server {
        listen 80;
        server_name app.netforge.test;
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
    server {
        listen 8443 ssl;
        server_name app.netforge.test;
        ssl_certificate /Users/alishagupta/netforge-certs/app.netforge.test.pem;
        ssl_certificate_key /Users/alishagupta/netforge-certs/app.netforge.test-key.pem;
        location / {
            proxy_pass http://backend_servers;
            add_header Cache-Control "public, max-age=60";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
